clear all;
clc;
M=0.5;
m=0.2;
b=0.1;
l=0.3;
I=0.0006;
g=9.81;
s = tf('s');
q = (M+m) *(I+m*l^2) - (m*l) ^2;
P_pend = (m*l*s/q)/ (s^3 + (b*(I + m*l^2)) *s^2/q - ((M + m) *m*g*l) *s/q - b*m*g*l/q);
Kp = 100;
Ki = 1;
Kd = 20;
C = pid (Kp, Ki, Kd);
P_cart = (((I+m*l^2)/ q) *s^2 - (m*g*l/q))/ (s^4 + (b*(I + m*l^2)) *s^3/q - ((M + m) *m*g*l) *s^2/q - b*m*g*l*s/q);
T2 = feedback (1, P_pend*C) *P_cart;
t = 0:0.01:5;
impulse (T2, t);
